security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    mongo_provider:
      mongodb:
        class: App\Document\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: mongo_provider
      entry_point: form_login
      form_login:
        login_path: app_login
        check_path: app_login
      logout:
        path: app_logout
        target: app_login
      # oauth:
      #   resource_owners:
      #     github: "/login/check-github"
      #   login_path: /login
      #   use_forward: false
      #   failure_path: /login
      #   oauth_user_provider:
      #     service: hwi_oauth.user.provider

  access_control:
    - { path: ^/brands, roles: ROLE_ADMIN }
    - { path: ^/customer, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
